// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from 'E:/Project portfolio/XFishBlog/blog-admin/frontedUserCenter/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import FileAddOutlined from 'E:/Project portfolio/XFishBlog/blog-admin/frontedUserCenter/node_modules/@ant-design/icons/es/icons/FileAddOutlined';
import MessageOutlined from 'E:/Project portfolio/XFishBlog/blog-admin/frontedUserCenter/node_modules/@ant-design/icons/es/icons/MessageOutlined';
import BarChartOutlined from 'E:/Project portfolio/XFishBlog/blog-admin/frontedUserCenter/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import UserOutlined from 'E:/Project portfolio/XFishBlog/blog-admin/frontedUserCenter/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { CrownOutlined, FileAddOutlined, MessageOutlined, BarChartOutlined, UserOutlined };
