// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"name":"register","path":"/user/register","parentId":"1","id":"3"},"4":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/admin/article","name":"文章管理","icon":"FileAdd","parentId":"4","id":"5"},"6":{"path":"/admin/comment","name":"评论管理","icon":"Message","parentId":"4","id":"6"},"7":{"path":"/admin/user-manage","name":"用户管理","icon":"User","parentId":"4","id":"7"},"8":{"parentId":"4","id":"8"},"9":{"path":"/","name":"行为统计","icon":"BarChart","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"*","layout":false,"id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Article__index" */'@/pages/Article/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Comment__index" */'@/pages/Comment/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Admin__UserManage__index" */'@/pages/Admin/UserManage/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Statistics__index" */'@/pages/Statistics/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'E:/Project portfolio/XFishBlog/blog-admin/frontedUserCenter/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
